version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pedidos_db
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672" # Painel de controle

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - servico-pedidos

  servico-pedidos:
    build: ./servico-pedidos
    ports:
      - "3002:3002"  # <-- ADICIONADO (Porta do Pedidos)
    environment:
      DB_HOST: postgres
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  servico-pagamentos:
    build: ./servico-pagamentos
    ports:
      - "3001:3001"  # <-- ADICIONADO (Porta do Pagamentos)
    depends_on:
      - rabbitmq
      - servico-frete

  servico-frete:
    build: ./servico-frete
    ports:
      - "3005:3005"  # <-- ADICIONADO (Porta do Frete)
    environment:
      - PROMO_FRETE_GRATIS=true
    depends_on:
      - rabbitmq