apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-config
  namespace: pedidos-veloz
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "pedidos_db" # Alinhado com o seu banco atual
  RABBITMQ_HOST: "rabbitmq-service"
  API_PORT: "3000"
  URL_SERVICO_ESTOQUE: "http://servico-estoque:3003" 
  URL_SERVICO_PAGAMENTOS: "http://servico-pagamentos:3001" 