apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-frete
  namespace: pedidos-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servico-frete
  template:
    metadata:
      labels:
        app: servico-frete
    spec:
      containers:
      - name: servico-frete
        image: loja-veloz-devops-servico-frete:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: pedidos-config
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "150m"
            memory: "128Mi"