apiVersion: v1
kind: Service
metadata:
  name: pedidos-service
  namespace: pedidos-veloz
spec:
  selector:
    app: pedidos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001 # Porta do Node.js de Pedidos
---
apiVersion: v1
kind: Service
metadata:
  name: estoque-service
  namespace: pedidos-veloz
spec:
  selector:
    app: estoque
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003 # Porta do Node.js de Estoque
---
apiVersion: v1
kind: Service
metadata:
  name: pagamentos-service
  namespace: pedidos-veloz
spec:
  selector:
    app: pagamentos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002 # Porta do Node.js de Pagamentos
---
apiVersion: v1
kind: Service
metadata:
  name: frete-service
  namespace: pedidos-veloz
spec:
  selector:
    app: frete
  ports:
    - protocol: TCP
      port: 80         # Porta que o Gateway vai chamar (http://frete-service)
      targetPort: 3005 # AJUSTADO: Porta real do seu código servico-frete