name: CI - Build e Teste

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build das Imagens (Teste)
        # Trocamos para 'docker compose' e adicionamos o caminho correto
        run: docker compose -f infra/compose/docker-compose.yml build

      - name: Linter e Testes
        run: |
          echo "Rodando verificações iniciais..."
          # Aqui futuramente você pode rodar os testes do FastAPI