name: CI - Build e Teste

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build das Imagens (Teste)
        # Removido o caminho 'infra/compose/' pois o arquivo não está lá
        # Se o docker-compose.yml estiver na raiz, o comando abaixo funciona:
        run: docker compose build

      - name: Linter e Testes
        run: |
          echo "Rodando verificações na Loja Veloz..."